# Generated by Django 5.2.8 on 2025-11-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('mean_iki', models.FloatField()),
                ('variance_iki', models.FloatField()),
                ('burstiness', models.FloatField()),
                ('total_keys', models.IntegerField()),
                ('backspace_rate', models.FloatField()),
                ('mouse_distance', models.FloatField()),
                ('click_rate', models.FloatField()),
                ('idle_time_ms', models.IntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
