# Generated by Django 5.2.8 on 2025-11-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricrecord',
            name='click_rate',
        ),
        migrations.RemoveField(
            model_name='biometricrecord',
            name='mean_iki',
        ),
        migrations.RemoveField(
            model_name='biometricrecord',
            name='mouse_distance',
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='backspaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='click_rate_per_sec',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='distance_px',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='mean_iki_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='mouse_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='backspace_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='burstiness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='idle_time_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='total_keys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='variance_iki',
            field=models.FloatField(default=0),
        ),
    ]
