# Generated by Django 5.2.8 on 2025-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricrecord',
            name='gaze',
            field=models.JSONField(default=dict),
        ),
    ]
