# Generated by Django 5.2.8 on 2025-11-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_biometricrecord_gaze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricrecord',
            name='gaze',
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='gaze_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='gaze_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='screen_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='screen_w',
            field=models.IntegerField(default=0),
        ),
    ]
