# Generated by Django 5.2.8 on 2025-11-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_biometricrecord_gaze_biometricrecord_gaze_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('gaze_x', models.FloatField()),
                ('gaze_y', models.FloatField()),
                ('screen_w', models.FloatField()),
                ('screen_h', models.FloatField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
